networks:
  tk_net:
    driver: bridge

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks: [tk_net]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  # api:
  #   build: ./api
  #   restart: unless-stopped
  #   env_file: []
  #   environment:
  #     PORT: ${API_PORT}
  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   # healthcheck: # ðŸ‘ˆ simple HTTP check
  #   #   test: ['CMD', 'sh', '-c', 'wget -qO- http://localhost:3001/healthz || exit 1']
  #   #   interval: 10s
  #   #   timeout: 3s
  #   #   retries: 10
  #   networks: [tk_net]

  client:
    build: ./
    restart: unless-stopped
    env_file: []
    environment:
      PORT: ${CLIENT_PORT}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # depends_on: [api]
    # healthcheck:
    #   test: ['CMD', 'sh', '-c', 'wget -qO- http://localhost:3000/healthz|| exit 1']
    #   interval: 10s
    #   timeout: 3s
    #   retries: 10
    networks: [tk_net]
